server:
  port: 8088

spring:
  application:
    name: springboot-music-plus
  datasource:
    name: test
    url: jdbc:mysql://82.156.124.246:3306/music?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: spm
    password: 83(FB2/ph}MX+
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml


  spring:
    servlet:
      multipart:
        max-file-size: 15MB
        max-request-size: 15MB